apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: server-backendconfig
  namespace: async-doctor
spec:
  healthCheck:
    requestPath: /api/health
    port: 80
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
